<?php
$z[0]=Array("global","",74,101);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",113,143);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",172,198);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",205,231);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",355,382);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",397,427);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",521,548);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",551,577);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",592,622);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",829,854);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("channel","\r\n        <li class=\"line\"></li>\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n     	",881,1037);
$z[10][4]['type']="top";
$z[10][4]['row']="10";
$z[11]=Array("arclist","\r\nlinkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\npicarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n",1596,1770);
$z[11][4]['flag']="f";
$z[11][4]['row']="5";
$z[11][4]['typeid']="13";
$z[12]=Array("global","",2344,2374);
$z[12][4]['name']="cfg_templeturl";
$z[13]=Array("global","",2697,2727);
$z[13][4]['name']="cfg_templeturl";

?>