<?php
$z[0]=Array("channel","\r\n		<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",201,323);
$z[0][4]['type']="son";
$z[0][4]['typeid']="2";
$z[1]=Array("type","[field:typeurl/]",458,509);
$z[1][4]['typeid']="11";
$z[2]=Array("global","",521,551);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("type","[field:typeurl/]",642,693);
$z[3][4]['typeid']="14";
$z[4]=Array("global","",705,735);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("mytag","",996,1030);
$z[5][4]['name']="左侧联系我们";

?>