<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",487,517);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("include","",604,639);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n		<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",900,1022);
$z[6][4]['type']="son";
$z[6][4]['typeid']="2";
$z[7]=Array("type","[field:typeurl/]",1157,1208);
$z[7][4]['typeid']="11";
$z[8]=Array("global","",1220,1250);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("type","[field:typeurl/]",1341,1392);
$z[9][4]['typeid']="14";
$z[10]=Array("global","",1404,1434);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("mytag","",1695,1729);
$z[11][4]['name']="左侧联系我们";
$z[12]=Array("type","[field:typename /]",1889,1930);
$z[13]=Array("list","\r\n      <li>\r\n<div class=\"photo\"><a href='[field:arcurl/]' title='[field:title/]' target='_blank'>\r\n<img src='[field:litpic/]' width='139' height='104'></a></div>\r\n  <p class=\"name\"><a href='[field:arcurl/]' title='[field:title/]' target='_blank'>[field:title/]</a></p>\r\n</li>\r\n                      \r\n        ",1993,2340);
$z[13][4]['pagesize']="18";
$z[14]=Array("pagelist","",2471,2543);
$z[14][4]['listitem']="info,index,end,pre,next,pageno";
$z[14][4]['listsize']="5";
$z[15]=Array("include","",2730,2765);
$z[15][4]['filename']="foot.htm";

?>